### ISSUE TITLE
关于数据大于200时获取问题

### ISSUE THREAD

**Issue by NikolaCavendish** [xiusin/redis_manager#34]
你好，我在使用过程中遇到一个问题
![image](https://github.com/xiusin/web-redis-manager/assets/76593191/85df66dd-48c8-4df2-b44b-3a57d8bce953)
在我点击箭头展开数据库时可以看到真实数据为323条
![image](https://github.com/xiusin/web-redis-manager/assets/76593191/f0276f2e-7083-46de-b7c8-fc403f49b44c)
点击这个node之后，只获取到200条数据，没有获取到其他的数据。

**Comment by NikolaCavendish** [comment]
我修改了后端的请求数量，似乎可以添加分页的功能，会更方便。

**Comment by xiusin** [comment]
@NikolaCavendish 这个好像是因为点击后拉取数据列表刷了一次总数导致的，最开始设计的是读取全量，但是页面会卡死，最近的一版改成了scan处理，所以读不全，如果你解决了可以PR一个合并下😂
